-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.branches (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  tenant_id uuid NOT NULL,
  name text NOT NULL,
  location text,
  created_at timestamp with time zone DEFAULT now(),
  location_id uuid,
  address text,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  phone text,
  CONSTRAINT branches_pkey PRIMARY KEY (id),
  CONSTRAINT branches_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT branches_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(id)
);
CREATE TABLE public.categories (
  id text NOT NULL,
  tenant_id uuid NOT NULL,
  name text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  synced_at timestamp with time zone,
  branch_id uuid,
  CONSTRAINT categories_pkey PRIMARY KEY (id),
  CONSTRAINT categories_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT categories_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id)
);
CREATE TABLE public.composite_item_components (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  composite_product_id uuid NOT NULL,
  component_product_id uuid NOT NULL,
  quantity integer NOT NULL,
  CONSTRAINT composite_item_components_pkey PRIMARY KEY (id),
  CONSTRAINT composite_item_components_composite_product_id_fkey FOREIGN KEY (composite_product_id) REFERENCES public.products(id),
  CONSTRAINT composite_item_components_component_product_id_fkey FOREIGN KEY (component_product_id) REFERENCES public.products(id)
);
CREATE TABLE public.credit_note_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  credit_note_id uuid NOT NULL,
  product_id uuid NOT NULL,
  product_name text,
  quantity integer NOT NULL DEFAULT 1 CHECK (quantity > 0),
  unit_price numeric NOT NULL DEFAULT 0,
  tax_amount numeric NOT NULL DEFAULT 0,
  total numeric NOT NULL DEFAULT 0,
  tenant_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT credit_note_items_pkey PRIMARY KEY (id),
  CONSTRAINT credit_note_items_credit_note_id_fkey FOREIGN KEY (credit_note_id) REFERENCES public.credit_notes(id),
  CONSTRAINT credit_note_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT credit_note_items_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.credit_notes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  tenant_id uuid NOT NULL,
  branch_id uuid,
  original_sale_id uuid NOT NULL,
  credit_number text,
  status text NOT NULL DEFAULT 'draft'::text,
  reason text NOT NULL DEFAULT ''::text,
  items jsonb NOT NULL DEFAULT '[]'::jsonb,
  subtotal numeric DEFAULT 0,
  tax_amount numeric DEFAULT 0,
  total numeric DEFAULT 0,
  applied_to_sale_id uuid,
  created_by uuid,
  approved_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  restock_items boolean DEFAULT false,
  CONSTRAINT credit_notes_pkey PRIMARY KEY (id),
  CONSTRAINT credit_notes_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT credit_notes_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id),
  CONSTRAINT credit_notes_original_sale_id_fkey FOREIGN KEY (original_sale_id) REFERENCES public.sales(id),
  CONSTRAINT credit_notes_applied_to_sale_id_fkey FOREIGN KEY (applied_to_sale_id) REFERENCES public.sales(id),
  CONSTRAINT credit_notes_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT credit_notes_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES auth.users(id)
);
CREATE TABLE public.customers (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  tenant_id uuid NOT NULL,
  name text NOT NULL,
  phone text,
  email text,
  loyalty_points integer DEFAULT 0,
  credit_limit numeric DEFAULT 0.00,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  branch_id uuid,
  CONSTRAINT customers_pkey PRIMARY KEY (id),
  CONSTRAINT customers_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT customers_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id)
);
CREATE TABLE public.item_groups (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  tenant_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  default_commission_type text,
  default_commission_value real,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  synced_at timestamp with time zone,
  branch_id uuid,
  attributes jsonb DEFAULT '[]'::jsonb,
  CONSTRAINT item_groups_pkey PRIMARY KEY (id),
  CONSTRAINT item_groups_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT item_groups_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id)
);
CREATE TABLE public.locations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  tenant_id uuid NOT NULL,
  name text NOT NULL,
  type text DEFAULT 'Region'::text,
  address text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  synced_at timestamp with time zone,
  CONSTRAINT locations_pkey PRIMARY KEY (id),
  CONSTRAINT locations_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.products (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  tenant_id uuid NOT NULL,
  name text NOT NULL,
  sku text,
  description text,
  base_price numeric DEFAULT 0.00,
  tax_category text DEFAULT 'VAT_16'::text,
  is_service boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  item_group_id uuid,
  commission_type text,
  commission_value real,
  image_url text,
  barcode text,
  category_id text,
  cost_price real,
  branch_id uuid,
  group_id uuid,
  variant_options jsonb,
  product_type text NOT NULL DEFAULT 'standard'::text,
  uom_id uuid,
  variant_images jsonb,
  parent_id uuid,
  CONSTRAINT products_pkey PRIMARY KEY (id),
  CONSTRAINT products_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT products_item_group_id_fkey FOREIGN KEY (item_group_id) REFERENCES public.item_groups(id),
  CONSTRAINT products_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id),
  CONSTRAINT products_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id),
  CONSTRAINT products_group_id_fkey FOREIGN KEY (group_id) REFERENCES public.stock_item_groups(id),
  CONSTRAINT products_uom_id_fkey FOREIGN KEY (uom_id) REFERENCES public.units_of_measurement(id),
  CONSTRAINT products_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.products(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  tenant_id uuid NOT NULL,
  branch_id uuid,
  role text DEFAULT 'Cashier'::text CHECK (role = ANY (ARRAY['Owner'::text, 'Manager'::text, 'Cashier'::text])),
  display_name text,
  created_at timestamp with time zone DEFAULT now(),
  profile_picture_url text,
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  permissions jsonb DEFAULT '[]'::jsonb,
  phone text,
  address text,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT profiles_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT profiles_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id)
);
CREATE TABLE public.sale_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  sale_id uuid NOT NULL,
  product_id uuid NOT NULL,
  quantity integer DEFAULT 1,
  unit_price numeric DEFAULT 0.00,
  tax_amount numeric DEFAULT 0.00,
  total numeric DEFAULT 0.00,
  tenant_id uuid,
  discount numeric DEFAULT 0,
  cost_price numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  product_name text,
  CONSTRAINT sale_items_pkey PRIMARY KEY (id),
  CONSTRAINT sale_items_sale_id_fkey FOREIGN KEY (sale_id) REFERENCES public.sales(id),
  CONSTRAINT sale_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT sale_items_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.sale_payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  sale_id uuid NOT NULL,
  tenant_id uuid NOT NULL,
  amount numeric NOT NULL,
  payment_method text NOT NULL,
  reference_number text,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  branch_id uuid,
  CONSTRAINT sale_payments_pkey PRIMARY KEY (id),
  CONSTRAINT sale_payments_sale_id_fkey FOREIGN KEY (sale_id) REFERENCES public.sales(id),
  CONSTRAINT sale_payments_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT sale_payments_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id)
);
CREATE TABLE public.sales (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  tenant_id uuid NOT NULL,
  branch_id uuid NOT NULL,
  customer_id uuid,
  total_amount numeric DEFAULT 0.00,
  payment_method text,
  status text DEFAULT 'Draft'::text,
  synced_at timestamp with time zone DEFAULT now(),
  external_ref text,
  created_at timestamp with time zone DEFAULT now(),
  invoice_number text,
  sale_type text NOT NULL DEFAULT 'sale'::text,
  created_by uuid,
  approved_by uuid,
  subtotal numeric DEFAULT 0,
  tax_amount numeric DEFAULT 0,
  discount_amount numeric DEFAULT 0,
  grand_total numeric DEFAULT 0,
  amount_paid numeric DEFAULT 0,
  notes text,
  due_date timestamp with time zone,
  completed_at timestamp with time zone,
  voided_at timestamp with time zone,
  void_reason text,
  updated_at timestamp with time zone DEFAULT now(),
  fulfillment_status text DEFAULT 'unfulfilled'::text,
  salesperson_id uuid,
  payment_status text NOT NULL DEFAULT 'unpaid'::text CHECK (payment_status = ANY (ARRAY['unpaid'::text, 'partially_paid'::text, 'paid'::text])),
  CONSTRAINT sales_pkey PRIMARY KEY (id),
  CONSTRAINT sales_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT sales_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id),
  CONSTRAINT sales_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT sales_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT sales_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES auth.users(id)
);
CREATE TABLE public.staff_members (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  tenant_id uuid NOT NULL,
  branch_id uuid,
  name text NOT NULL,
  phone text,
  email text,
  profile_picture_url text,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT staff_members_pkey PRIMARY KEY (id),
  CONSTRAINT staff_members_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id),
  CONSTRAINT staff_members_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.stock (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  tenant_id uuid NOT NULL,
  branch_id uuid NOT NULL,
  product_id uuid NOT NULL,
  quantity integer DEFAULT 0,
  reorder_level integer DEFAULT 5,
  last_updated timestamp with time zone DEFAULT now(),
  CONSTRAINT stock_pkey PRIMARY KEY (id),
  CONSTRAINT stock_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT stock_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id),
  CONSTRAINT stock_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.stock_adjustment_reasons (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  label text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT stock_adjustment_reasons_pkey PRIMARY KEY (id)
);
CREATE TABLE public.stock_adjustments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  tenant_id uuid NOT NULL,
  branch_id uuid NOT NULL,
  product_id uuid NOT NULL,
  adjustment_type text NOT NULL CHECK (adjustment_type = ANY (ARRAY['addition'::text, 'reduction'::text, 'initial'::text, 'damage'::text])),
  quantity integer NOT NULL,
  reference_number text,
  notes text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  reason_id uuid,
  CONSTRAINT stock_adjustments_pkey PRIMARY KEY (id),
  CONSTRAINT stock_adjustments_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT stock_adjustments_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id),
  CONSTRAINT stock_adjustments_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT stock_adjustments_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT stock_adjustments_reason_id_fkey FOREIGN KEY (reason_id) REFERENCES public.stock_adjustment_reasons(id)
);
CREATE TABLE public.stock_item_groups (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  attributes jsonb,
  CONSTRAINT stock_item_groups_pkey PRIMARY KEY (id)
);
CREATE TABLE public.tenant_invoice_counters (
  tenant_id uuid NOT NULL,
  prefix text NOT NULL DEFAULT 'INV'::text,
  year integer NOT NULL,
  last_seq integer NOT NULL DEFAULT 0,
  CONSTRAINT tenant_invoice_counters_pkey PRIMARY KEY (tenant_id, prefix, year),
  CONSTRAINT tenant_invoice_counters_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.tenants (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  plan_type text DEFAULT 'Basic'::text,
  created_at timestamp with time zone DEFAULT now(),
  address text,
  phone text,
  email text,
  logo_url text,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  CONSTRAINT tenants_pkey PRIMARY KEY (id)
);
CREATE TABLE public.units_of_measurement (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  label text NOT NULL,
  abbreviation text,
  base_unit_id uuid,
  conversion_factor real DEFAULT 1.0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT units_of_measurement_pkey PRIMARY KEY (id),
  CONSTRAINT units_of_measurement_base_unit_id_fkey FOREIGN KEY (base_unit_id) REFERENCES public.units_of_measurement(id)
);